version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: analytics_dev/Dockerfile
      args:
        PYTHON_VARIANT: 3.9
        JAVA_VARIANT: 11-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  pyspark:
    image: jupyter/pyspark-notebook:spark-3.2.1
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    ports: 
      - 8889:8888